# Jitsi Meet 会议系统
version: '3.8'

services:
  # Jitsi Web前端
  web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./config/web:/config:Z
      - ./config/web/letsencrypt:/etc/letsencrypt:Z
      - ./config/transcripts:/usr/share/jitsi-meet/transcripts:Z
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_LETSENCRYPT=0
      - ENABLE_HTTP_REDIRECT=0
      - ENABLE_HSTS=0
      - DISABLE_HTTPS=0
      - LETSENCRYPT_DOMAIN=${JITSI_DOMAIN:-meet.localhost}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@localhost}
      - PUBLIC_URL=https://${JITSI_DOMAIN:-meet.localhost}
      - TZ=${TZ:-Asia/Shanghai}
      - AMPLITUDE_ID
      - ANALYTICS_SCRIPT_URLS
      - ANALYTICS_WHITELISTED_EVENTS
      - BRIDGE_CHANNEL
      - BRANDING_DATA_URL
      - CALLSTATS_CUSTOM_SCRIPT_URL
      - CALLSTATS_ID
      - CALLSTATS_SECRET
      - CHROME_EXTENSION_BANNER_JSON
      - CONFCODE_URL
      - CONFIG_EXTERNAL_CONNECT
      - DEFAULT_LANGUAGE
      - DEPLOYMENTINFO_ENVIRONMENT
      - DEPLOYMENTINFO_ENVIRONMENT_TYPE
      - DEPLOYMENTINFO_REGION
      - DEPLOYMENTINFO_SHARD
      - DEPLOYMENTINFO_USERREGION
      - DIALIN_NUMBERS_URL
      - DIALOUT_AUTH_URL
      - DIALOUT_CODES_URL
      - DROPBOX_APPKEY
      - DROPBOX_REDIRECT_URL
      - DYNAMIC_BRANDING_URL
      - ENABLE_AUDIO_PROCESSING
      - ENABLE_AUTH
      - ENABLE_CALENDAR
      - ENABLE_FILE_RECORDING_SERVICE
      - ENABLE_FILE_RECORDING_SERVICE_SHARING
      - ENABLE_GUESTS
      - ENABLE_IPV6
      - ENABLE_LIPSYNC
      - ENABLE_NO_AUDIO_DETECTION
      - ENABLE_P2P
      - ENABLE_PREJOIN_PAGE
      - ENABLE_WELCOME_PAGE
      - ENABLE_CLOSE_PAGE
      - ENABLE_RECORDING
      - ENABLE_REMB
      - ENABLE_REQUIRE_DISPLAY_NAME
      - ENABLE_SIMULCAST
      - ENABLE_STATS_ID
      - ENABLE_STEREO
      - ENABLE_SUBDOMAINS
      - ENABLE_TALK_WHILE_MUTED
      - ENABLE_TCC
      - ENABLE_TRANSCRIPTIONS
      - ETHERPAD_PUBLIC_URL
      - ETHERPAD_URL_BASE
      - GOOGLE_ANALYTICS_ID
      - GOOGLE_API_APP_CLIENT_ID
      - HIDE_PREMEETING_BUTTONS
      - INVITE_SERVICE_URL
      - JICOFO_AUTH_USER
      - MATOMO_ENDPOINT
      - MATOMO_SITE_ID
      - MICROSOFT_API_APP_CLIENT_ID
      - NGINX_RESOLVER
      - NGINX_WORKER_CONNECTIONS
      - NGINX_WORKER_PROCESSES
      - PEOPLE_SEARCH_URL
      - RESOLUTION
      - RESOLUTION_MIN
      - RESOLUTION_WIDTH
      - RESOLUTION_WIDTH_MIN
      - START_AUDIO_ONLY
      - START_AUDIO_MUTED
      - START_WITH_AUDIO_MUTED
      - START_SILENT
      - DISABLE_AUDIO_LEVELS
      - ENABLE_NOISY_MIC_DETECTION
      - START_BITRATE
      - DESKTOP_SHARING_FRAMERATE_MIN
      - DESKTOP_SHARING_FRAMERATE_MAX
      - START_VIDEO_MUTED
      - START_WITH_VIDEO_MUTED
      - TESTING_CAP_SCREENSHARE_BITRATE
      - TESTING_OCTO_PROBABILITY
      - XMPP_AUTH_DOMAIN
      - XMPP_BOSH_URL_BASE
      - XMPP_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - TOKEN_AUTH_URL
    depends_on:
      - prosody
      - jicofo
      - jvb
    networks:
      - jitsi-network

  # Prosody XMPP服务器
  prosody:
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    restart: unless-stopped
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ./config/prosody/config:/config:Z
      - ./config/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - GLOBAL_MODULES
      - GLOBAL_CONFIG
      - LDAP_URL
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_AUTH_METHOD
      - LDAP_VERSION
      - LDAP_USE_TLS
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - XMPP_DOMAIN=${JITSI_DOMAIN:-meet.localhost}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_GUEST_DOMAIN=guest.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_MUC_DOMAIN=muc.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN=recorder.${JITSI_DOMAIN:-meet.localhost}
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JIGASI_XMPP_USER=jigasi
      - JIGASI_XMPP_PASSWORD=${JIGASI_XMPP_PASSWORD}
      - JIBRI_RECORDER_USER=recorder
      - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD}
      - JIBRI_XMPP_USER=jibri
      - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD}
      - ENABLE_LOBBY=1
      - ENABLE_AV_MODERATION=1
      - ENABLE_BREAKOUT_ROOMS=1
      - ENABLE_END_CONFERENCE=0
      - ENABLE_GUESTS_DOMAIN=1
      - ENABLE_RECORDING=0
      - ENABLE_REMB=1
      - ENABLE_XMPP_WEBSOCKET=1
      - PUBLIC_URL=https://${JITSI_DOMAIN:-meet.localhost}
      - TZ=${TZ:-Asia/Shanghai}
    networks:
      - jitsi-network

  # Jicofo会议焦点组件
  jicofo:
    image: jitsi/jicofo:stable
    container_name: jitsi-jicofo
    restart: unless-stopped
    volumes:
      - ./config/jicofo:/config:Z
    environment:
      - ENABLE_AUTH=0
      - XMPP_DOMAIN=${JITSI_DOMAIN:-meet.localhost}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_MUC_DOMAIN=muc.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_SERVER=prosody
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS=true
      - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT=15000
      - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT=0
      - JICOFO_ENABLE_HEALTH_CHECKS=true
      - JICOFO_SHORT_ID
      - JICOFO_RESERVATION_ENABLED
      - JICOFO_RESERVATION_REST_BASE_URL
      - JIBRI_BREWERY_MUC
      - JIBRI_REQUEST_RETRIES
      - JIBRI_PENDING_TIMEOUT
      - JIGASI_BREWERY_MUC
      - JIGASI_SIP_URI
      - TZ=${TZ:-Asia/Shanghai}
    depends_on:
      - prosody
    networks:
      - jitsi-network

  # JVB视频桥接服务器
  jvb:
    image: jitsi/jvb:stable
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    volumes:
      - ./config/jvb:/config:Z
    environment:
      - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN:-meet.localhost}
      - XMPP_SERVER=prosody
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_TCP_PORT=4443
      - JVB_TCP_MAPPED_PORT=4443
      - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
      - ENABLE_COLIBRI_WEBSOCKET=1
      - ENABLE_OCTO=1
      - TZ=${TZ:-Asia/Shanghai}
    depends_on:
      - prosody
    networks:
      - jitsi-network

networks:
  jitsi-network:
    driver: bridge

volumes:
  jitsi-config:
    driver: local